version: '2'
services:
  web:
    build:
      context: .
    #ports:
    #  - 3000:3000
    command: |
      cp public/config/config_dev.json public/config/config.json
      yarn build
      nohup serve -s ./build -p 3000 &
      yarn cypress:ci
    # environment:
      #- PUBLIC_URL=/talentmap/
      #- STATIC_PATH=/app/build/
      #- API_ROOT=http://api:8000/
    volumes:
      - .:/app:delegated
      - node-modules:/app/node_modules/
volumes:
  node-modules:
