version: '2'
services:
  web:
    build:
      context: .
    #ports:
    #  - 3000:3000
    command: >
      bash -c "cp public/config/config_dev.json public/config/config.json
      && yarn build
      && serve -s ./build -p 3000"
    # environment:
      #- PUBLIC_URL=/talentmap/
      #- STATIC_PATH=/app/build/
      #- API_ROOT=http://api:8000/
    networks:
      - network
    volumes:
      - .:/app:delegated
      - node-modules:/app/node_modules/
volumes:
  node-modules:
networks:
  network:
    external:
      name: state-talentmap-api_default
