version: 2.1
default-docker-node: &default-docker-node
  docker:
    - image: circleci/node:12.13.0
      environment:
        TZ: "/usr/share/zoneinfo/America/New_York"
        CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
        COMPOSE_FILE_NAME: circleci-docker-compose.yml
        API_REPO_NAME: state-talentmap-api
        API_REPO_BRANCH: staging
        PUBLIC_URL: /talentmap/
        STATIC_PATH: /home/circleci/project/public
        API_ROOT: http://app:8000/
jobs:
  build:
    <<: *default-docker-node
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-
      - run: yarn install --pure-lockfile
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ~/.cache/yarn
  docker-build:
    <<: *default-docker-node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Build
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            BRANCH=${CIRCLE_BRANCH//\//-}
            TAG=$BRANCH-$CIRCLE_SHA1
            DOCKER_HUB_REPO=${CIRCLE_PROJECT_REPONAME,,}
            docker build -t talentmap/$DOCKER_HUB_REPO:$TAG .
            docker push talentmap/$DOCKER_HUB_REPO:$TAG
  yarn:
    <<: *default-docker-node
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: chmod +x ./certs/certs.sh
      - run: cd certs && ./certs.sh
      - run: cd ..
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --pure-lockfile
      - run:
          name: Install JUnit coverage reporter
          command: yarn add --dev jest-junit@8.0.0
      - run:
          name: Jest Test Coverage
          command: yarn test -- --ci --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_NAME: "reports/jest/test-results.xml"
      - run: ./cc-test-reporter after-build --exit-code $? < coverage/lcov.info
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov.info
          destination: coverage/lcov.info
  site:
    <<: *default-docker-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --pure-lockfile
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run:
          name: Build site
          command: yarn build
      - run:
          name: Zip artifact
          command: zip talentmap.zip -r build/*
      - store_artifacts:
          path: talentmap.zip
          destination: talentmap.zip
  server:
    <<: *default-docker-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build server
          command: mkdir server && cp package.json src/server.js src/saml2-config.js src/routes.js server/
      - run:
          name: Install dependencies
          command: yarn install --production=true --no-lockfile --modules-folder server/node_modules/
      - run:
          name: Zip artifact
          command: zip talentmap-server.zip -r server/*
      - store_artifacts:
          path: talentmap-server.zip
          destination: talentmap-server.zip
 # Disabled see 1368 pa11y:
 #   <<: *default-docker-node
 #   steps:
 #     - setup_remote_docker
 #     - checkout
 #     - run:
 #         name: Replace placeholders in Compose file
 #         command: |
 #           TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1
 #           sed -i "s#@@LABEL@@#${TAG}#g" $COMPOSE_FILE_NAME
 #           sed -i "s#@@REPO_NAME@@#${CIRCLE_PROJECT_REPONAME,,}#g" $COMPOSE_FILE_NAME
 #           sed -i "s#@@API_REPO_NAME@@#${API_REPO_NAME}#g" $COMPOSE_FILE_NAME
 #           sed -i "s#@@API_REPO_BRANCH@@#${API_REPO_BRANCH}#g" $COMPOSE_FILE_NAME
 #     - run:
 #         name: Initialize Dummy Data Container
 #         command: |
 #           docker-compose -f $COMPOSE_FILE_NAME create data
 #           docker cp . data:/app
 #     - run:
 #         name: Migrate DB
 #         command: |
 #           docker-compose -f $COMPOSE_FILE_NAME \
 #             run app bash -c \
 #             "./wait-for-postgres.sh db && python manage.py migrate"
 #     - run:
 #         name: Run Yarn
 #         command: |
 #           docker-compose -f $COMPOSE_FILE_NAME \
 #             run web yarn
 #     - run:
 #         name: Start Server
 #         command: docker-compose -f $COMPOSE_FILE_NAME up -d
 #     - run:
 #         name: Run Pa11y
 #         command: |
 #           docker run --name pa11y --network container:web \
 #             --volumes-from data -t talentmap/pa11y-ci \
 #             pa11y-ci -c /app/.pa11yci
  cypress:
    <<: *default-docker-node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Replace placeholders in Compose file
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1
            sed -i "s#@@LABEL@@#${TAG}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@REPO_NAME@@#${CIRCLE_PROJECT_REPONAME}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@API_REPO_NAME@@#${API_REPO_NAME}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@API_REPO_BRANCH@@#${API_REPO_BRANCH}#g" $COMPOSE_FILE_NAME
      - run:
          name: Install dependencies
          command: yarn install --pure-lockfile
      - run:
          name: Replace config.json
          command: cp ${STATIC_PATH}/config_dev.json ${STATIC_PATH/config.json}
      - run:
          name: Install cypress dependencies
          command: sudo apt-get install libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Run server
          command: yarn run server
      - run:
          name: Start server and run Cypress
          command: yarn cypress:ci
  zap:
    <<: *default-docker-node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Replace placeholders in Compose file
          command: |
            TAG=$CIRCLE_BRANCH-$CIRCLE_SHA1
            sed -i "s#@@LABEL@@#${TAG}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@REPO_NAME@@#${CIRCLE_PROJECT_REPONAME}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@API_REPO_NAME@@#${API_REPO_NAME}#g" $COMPOSE_FILE_NAME
            sed -i "s#@@API_REPO_BRANCH@@#${API_REPO_BRANCH}#g" $COMPOSE_FILE_NAME
      - run:
          name: Initialize Dummy Data Container
          command: |
            docker-compose -f $COMPOSE_FILE_NAME create data
            docker cp . data:/app
      - run:
          name: Migrate DB
          command: |
            docker-compose -f $COMPOSE_FILE_NAME \
              run app bash -c \
              "./wait-for-postgres.sh db && python manage.py migrate"
      - run:
          name: Run Yarn
          command: |
            docker-compose -f $COMPOSE_FILE_NAME \
              run web yarn
      - run:
          name: Start Server
          command: docker-compose -f $COMPOSE_FILE_NAME up -d
      - run:
          name: Run ZAP
          command: |
            docker run --name zap --network container:web \
              -v /zap/wrk/ \
              -t owasp/zap2docker-weekly \
              zap-baseline.py -d \
                -t http://web:3000/ \
                -w "zap_results.md" \
                -z "-Xmx4g"
  push-stable:
    <<: *default-docker-node
    steps:
      - setup_remote_docker
      - run:
          name: Push Stable Docker Image
          command: |
            BRANCH=${CIRCLE_BRANCH//\//-}
            TAG=$BRANCH-$CIRCLE_SHA1
            DOCKER_HUB_REPO=${CIRCLE_PROJECT_REPONAME,,}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull talentmap/$DOCKER_HUB_REPO:$TAG
            docker tag talentmap/$DOCKER_HUB_REPO:$TAG talentmap/$DOCKER_HUB_REPO:$BRANCH
            docker push talentmap/$DOCKER_HUB_REPO:$BRANCH
  deploy:
    <<: *default-docker-node
    steps:
      - add_ssh_keys
      - run:
          command: ssh -o StrictHostKeyChecking=no ec2-user@ec2-52-204-49-159.compute-1.amazonaws.com ./deploy.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - docker-build:
          requires:
            - build
          # filters:
            # branches:
              # only:
                # - dev
                # - staging
                # - master
      - yarn:
          requires:
            - build
      - site:
          requires:
            - yarn
            - build
      # Disabled
      - cypress:
          requires:
            - yarn
      - server:
          requires:
            - yarn
      # Disabled see 1368 - pa11y:
      #    requires:
      #      - docker-build
      - deploy:
          requires:
            - yarn
          filters:
            branches:
              only: dev
      - zap:
          requires:
            - docker-build
          filters:
            tags:
              only: /^zap.*/
            branches:
              ignore: /.*/
      - push-stable:
          requires:
            - yarn
            # Disabled see 1368 - pa11y
          filters:
            branches:
              only:
                - dev
                - staging
                - master
