import {
  cableFetchData,
  cableFetchDataErrored,
  cableFetchDataLoading,
  getGal,
  getGalErrored,
  getGalLoading,
  getOpsData,
  getOpsDataErrored,
  getOpsDataLoading,
  getOpsWsdl,
  getOpsWsdlErrored,
  getOpsWsdlLoading,
  noteCableFetchData,
  noteCableFetchDataErrored,
  noteCableFetchDataLoading,
  noteCableRefFetchData,
  noteCableRefFetchDataErrored,
  noteCableRefFetchDataLoading,
} from './assignmentNotifications';

export default {
  cableFetchData,
  cableFetchDataErrored,
  cableFetchDataLoading,
  getGal,
  getGalErrored,
  getGalLoading,
  getOpsData,
  getOpsDataErrored,
  getOpsDataLoading,
  getOpsWsdl,
  getOpsWsdlErrored,
  getOpsWsdlLoading,
  noteCableFetchData,
  noteCableFetchDataErrored,
  noteCableFetchDataLoading,
  noteCableRefFetchData,
  noteCableRefFetchDataErrored,
  noteCableRefFetchDataLoading,
};
