name: size-label
on:
  pull_request:
    branches-ignore:
      - 'dependabot/*'
    paths-ignore:
      - '**__snapshots__**'
      - '**.snap'
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.3"
        if: ${{ github.actor != 'dependabot[bot]' }} # Skip the action if the PR was created by Dependabot.
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: "**.snap/**"
#           IGNORED: "*.snap/**"
#           IGNORED: "**.snap"
#           IGNORED: "*.snap"


#          IGNORED: "*.snap\n**.snap\n.*.snap\n.jxs\njsx\n*.jsx\n**.jsx\ngenerated/**"
#          IGNORED: "*.snap\n**.snap\n.*.snap\n.jxs\njsx\n*.jsx\n**.jsx\ngenerated/**"
#          IGNORED: "*.snap\n**.snap\n.*.snap\n.jxs\njsx\n*.jsx\n**.jsx\ngenerated/**"
        with:
          sizes: >
            {
              "2": "XS",
              "4": "S",
              "6": "M",
              "8": "L",
              "10": "XL",
              "12": "XXL"
            }
